# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemInfo',
            fields=[
                ('STU_ID', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('NAME', models.CharField(max_length=32)),
                ('GENDER', models.CharField(max_length=4)),
                ('MEM_TYPE', models.IntegerField()),
                ('PHONE', models.CharField(max_length=11)),
                ('EMAIL', models.EmailField(max_length=256)),
                ('TS_CREATED', models.DateTimeField(auto_now_add=True)),
                ('TS_UPDATED', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AfterDistAnalysis',
            fields=[
                ('STU_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo')),
                ('OP_STU_ID', models.CharField(max_length=9)),
                ('DISTANCE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('DIST_RNK', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MchResult',
            fields=[
                ('STU_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo')),
                ('OP_STU_ID', models.CharField(max_length=9)),
                ('GROUP', models.IntegerField()),
                ('FINAL_RANK', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemMchInfo',
            fields=[
                ('STU_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo')),
                ('MY_GENDER', models.CharField(max_length=2)),
                ('MY_AGE', models.IntegerField()),
                ('MY_GRADE', models.IntegerField()),
                ('MY_CLEAN', models.CharField(max_length=48)),
                ('MY_YASIK', models.CharField(max_length=48)),
                ('MY_CHARACTER', models.CharField(max_length=256)),
                ('MY_OUTSIDE_ACTIVITY', models.IntegerField()),
                ('MY_FREQ_DRINK', models.CharField(max_length=32)),
                ('MY_DRINK', models.IntegerField()),
                ('MY_SMOKE', models.CharField(max_length=8)),
                ('OP_AGE', models.IntegerField()),
                ('OP_GRADE', models.IntegerField()),
                ('OP_CLEAN', models.CharField(max_length=48)),
                ('OP_YASIK', models.CharField(max_length=48)),
                ('OP_OUTSIDE_ACTIVITY', models.IntegerField()),
                ('OP_FREQ_DRINK', models.CharField(max_length=32)),
                ('OP_DRINK', models.IntegerField()),
                ('OP_SMOKE', models.CharField(max_length=8)),
                ('AGREE_WITH', models.CharField(max_length=32)),
                ('TS_CREATED', models.DateTimeField(auto_now_add=True)),
                ('TS_UPDATED', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreDistAnalysis',
            fields=[
                ('STU_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo')),
                ('MY_GENDER', models.IntegerField()),
                ('MY_CHARACTER_F', models.IntegerField()),
                ('MY_NEW_CLEAN_F', models.IntegerField()),
                ('MY_YASIK_F', models.IntegerField()),
                ('MY_OUTSIDE_ACTIVITY_F', models.IntegerField()),
                ('MY_FREQ_DRINK_F', models.IntegerField()),
                ('MY_DRINK_F', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WantnessAnalysis',
            fields=[
                ('STU_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo')),
                ('GENDER', models.IntegerField()),
                ('AGE_SCORE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('GRADE_SCORE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('CLEAN_SCORE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('YASIK_SCORE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('FREQ_DRINK_SCORE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('SMOKE_SCORE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('AGREE_SCORE', models.DecimalField(decimal_places=4, max_digits=4)),
                ('WANT_RNK', models.IntegerField()),
            ],
        ),
    ]
