# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meminfo',
            name='MEM_TYPE',
        ),
    ]
