# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_remove_meminfo_mem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afterdistanalysis',
            old_name='STU_ID',
            new_name='STUD_ID',
        ),
        migrations.RenameField(
            model_name='mchresult',
            old_name='STU_ID',
            new_name='STUD_ID',
        ),
        migrations.RenameField(
            model_name='meminfo',
            old_name='STU_ID',
            new_name='STUD_ID',
        ),
        migrations.RenameField(
            model_name='memmchinfo',
            old_name='STU_ID',
            new_name='STUD_ID',
        ),
        migrations.RenameField(
            model_name='predistanalysis',
            old_name='STU_ID',
            new_name='STUD_ID',
        ),
        migrations.RenameField(
            model_name='wantnessanalysis',
            old_name='STU_ID',
            new_name='STUD_ID',
        ),
        migrations.AddField(
            model_name='meminfo',
            name='ID',
            field=models.CharField(default='0', max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='meminfo',
            name='MAJOR',
            field=models.CharField(default='통계학과', max_length=48),
        ),
        migrations.AddField(
            model_name='meminfo',
            name='PWD',
            field=models.CharField(default='0', max_length=24),
        ),
    ]
