# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_auto_20180531_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afterdistanalysis',
            old_name='OP_STU_ID',
            new_name='OP_STUD_ID',
        ),
        migrations.RenameField(
            model_name='mchresult',
            old_name='OP_STU_ID',
            new_name='OP_STUD_ID',
        ),
    ]
