# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_auto_20180601_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='AGE_SCORE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='AGREE_SCORE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='CLEAN_SCORE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='FREQ_DRINK_SCORE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='GRADE_SCORE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='SMOKE_SCORE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='WANT_RNK',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='YASIK_SCORE',
            field=models.IntegerField(),
        ),
    ]
