# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_mchresult_ts_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memmchinfo',
            name='TS_CREATED',
        ),
    ]
