# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_remove_memmchinfo_ts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterdistanalysis',
            name='STUD_ID',
            field=models.OneToOneField(db_column='STUD_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo'),
        ),
        migrations.AlterField(
            model_name='mchresult',
            name='STUD_ID',
            field=models.OneToOneField(db_column='STUD_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo'),
        ),
        migrations.AlterField(
            model_name='memmchinfo',
            name='STUD_ID',
            field=models.OneToOneField(db_column='STUD_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo'),
        ),
        migrations.AlterField(
            model_name='predistanalysis',
            name='STUD_ID',
            field=models.OneToOneField(db_column='STUD_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo'),
        ),
        migrations.AlterField(
            model_name='wantnessanalysis',
            name='STUD_ID',
            field=models.OneToOneField(db_column='STUD_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluster.MemInfo'),
        ),
    ]
