# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0009_auto_20180602_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memmchinfo',
            name='TS_UPDATED',
        ),
    ]
